version: '3'
services:
  web:
    build: .
    image: 127.0.0.1:5000/lookatmy.frontend:dev
    ports:
      - "3001:3001"
    environment:
      - REDIS_API_URL=redis://redis_api:6379/0
      - PORT
    depends_on:
      - redis_api
  redis_api:
    image: redis:alpine